
spring:
  application:
    name: demo-consume
  cloud:
    nacos:
      discovery:
        #        username:
        #        password:
        server-addr: 192.168.56.1:8848
        group: DEV-GROUP
dubbo:
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  cloud:
    # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
    subscribed-services: demo-service
#  scan:
    # dubbo 服务扫描基准包
#    base-packages: com.example.service.impl
server:
  port: 8089